# Generated by Django 5.0.6 on 2024-06-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User1',
        ),
    ]
